title: ポちのDeepResearch
description: DeepResearchの結果を個人的にまとめたサイト
theme: jekyll-theme-cayman

# GitHub Pagesの設定
baseurl: "/share-deepresearch"
url: ""

# ナビゲーションの設定
collections:
  topics:
    output: true
    permalink: /topics/:path/

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

# 日付フォーマットの設定
timezone: Asia/Tokyo

# 音声ファイルなどのメディアファイルを含むディレクトリを指定
include:
  - _topics
  - "**/*.mp3"
  - "**/*.md"

# メディアファイルの処理を許可
keep_files:
  - .mp3

# メディアファイルの設定
defaults:
  - scope:
      path: "**/*.mp3"
    values:
      sitemap: false

# 日本語設定
lang: ja
encoding: UTF-8
